[package]
name = "mediasox"
description = "MediaScript library for audio manipulation using SoX"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
