[package]
name = "mediacomp"
description = "MediaScript library for 2D compositing of video"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
