[package]
name = "mediascript"
description = "Standard library for media editing with mediascript"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
itertools = "0.13.0"
regex = "1.11.1"
